# Generated by Django 5.2.1 on 2025-12-01 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tailor_booking_system_app', '0002_addnotification_admin_designer_registration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
