# Generated by Django 5.2.1 on 2025-12-15 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tailor_booking_system_app', '0005_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='designer',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
