# Generated by Django 5.2.1 on 2025-12-03 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_tailor_booking_system_app', '0004_booking_actual_start_date_booking_expected_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
